# Setup
setup: multi_task

# Database
train_db_name: PASCALContext
val_db_name: PASCALContext
trBatch: 12
valBatch: 12
nworkers: 4

# Optimizer and scheduler
epochs: 20
optimizer: sgd
optimizer_kwargs:
   lr: 0.005
   weight_decay: 0.0001
   momentum: 0.9
   nesterov: False
scheduler: poly

# Model
model: cross_stitch
model_kwargs:
   cross_stitch_kwargs: 
      alpha: 0.8
      beta: 0.05
      stages: ['layer1', 'layer2', 'layer3', 'layer4']
      channels:
         layer1: 64
         layer2: 128
         layer3: 256
         layer4: 512
backbone: resnet18
backbone_kwargs:
   pretrained: True
   dilated: True
head: deeplab

# Tasks
task_dictionary:
   include_semseg: True
   include_human_parts: True
   include_sal: True
   include_edge: True
   include_normals: True
   edge_w: 0.95

# Loss kwargs
loss_kwargs:
   loss_scheme: baseline
   loss_weights:
       semseg: 1.0
       human_parts: 2.0
       sal: 5.0
       edge: 50.0
       normals: 10.0
