# Setup
setup: single_task

# Database
train_db_name: NYUD
val_db_name: NYUD 
trBatch: 8
valBatch: 8
nworkers: 4

# Optimizer and scheduler
epochs: 100
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
scheduler: poly

# Model
model: baseline
backbone: resnet50
backbone_kwargs:
   pretrained: True
   dilated: True
head: deeplab

# Tasks
task_dictionary:
   include_semseg: True
