# Setup
setup: multi_task

# Database
train_db_name: KITTI
val_db_name: KITTI
trBatch: 2
valBatch: 2
nworkers: 4

# Optimizer and scheduler
epochs: 20
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
scheduler: poly

# Model
model: mti_net
backbone: hrnet_w64
# backbone: resnet50
backbone_kwargs:
   pretrained: True
   dilated: False
# head: hrnet
head: hrnet

# Tasks
task_dictionary:
   include_semseg: True
   include_depth: True

auxilary_task_dictionary:
   include_semseg: True
   include_depth: True

# Loss kwargs
loss_kwargs:
   loss_scheme: mti_net
   loss_weights:
       semseg: 1.0
       depth: 0.2

# Eval only final 10 epochs for speed-up
eval_final_10_epochs_only: False