# Setup
setup: single_task

# Database
train_db_name: KITTI
val_db_name: KITTI 
trBatch: 2
valBatch: 4
nworkers: 4

# Optimizer and scheduler
epochs: 20
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
scheduler: poly

# Model
model: baseline
backbone: hrnet_w64
backbone_kwargs:
   pretrained: True
   dilated: False
head: hrnet

# Tasks
task_dictionary:
   include_semseg: True

# Eval only final 10 epochs for speed-up
eval_final_10_epochs_only: False