# Setup
setup: multi_task

# Database
train_db_name: PASCALContext
val_db_name: PASCALContext
trBatch: 8
valBatch: 8
nworkers: 4

# Optimizer and scheduler
epochs: 100
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
scheduler: poly

# Model
model: mti_net 
backbone: hrnet_w18
backbone_kwargs:
   pretrained: True
   dilated: False
head: hrnet

# Tasks
task_dictionary:
   include_semseg: True
   include_human_parts: True
   include_sal: True
   include_edge: True
   include_normals: True
   edge_w: 0.95

auxilary_task_dictionary:
   include_semseg: True
   include_human_parts: True
   include_sal: True
   include_normals: True
   include_edge: True
   edge_w: 0.95 # Copy of task dictionary

# Loss kwargs
loss_kwargs:
   loss_scheme: mti_net
   loss_weights:
       semseg: 1.0
       human_parts: 2.0
       sal: 5.0
       edge: 50.0
       normals: 10.0

# Eval only final 10 epochs for speed-up
eval_final_10_epochs_only: True
