# Setup
setup: single_task

# Database
train_db_name: KITTI
val_db_name: KITTI 
trBatch: 8
valBatch: 8
nworkers: 4

# Optimizer and scheduler
epochs: 5
optimizer: adam
optimizer_kwargs:
   lr: 0.0005
   weight_decay: 0.0005
scheduler: poly

# Model
model: baseline
backbone: hrnet_w18
backbone_kwargs:
   pretrained: True
   dilated: False
head: hrnet

# Tasks
task_dictionary:
   include_depth: True
